version: '2'
services:
  storage:
    container_name: minio
    image: minio/minio
    environment:
    - MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F
    - MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    # - MINIO_IDENTITY_OPENID_CONFIG_URL=http://keycloak:8080/auth/realms/filestash/.well-known/openid-configuration
    # - MINIO_IDENTITY_OPENID_REDIRECT_URI=http://127.0.0.1:9001/oauth_callback
    # - MINIO_IDENTITY_OPENID_CLIENT_ID=filestash
    command: server /data --console-address ":9001"
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - ./volumes/minio:/data
    
  auth:
    container_name: keycloak
    image: jboss/keycloak
    volumes:
    - ./volumes/keycloak/:/opt/jboss/keycloak/standalone/data/
    ports:
    - 8080:8080
